### ISSUE TITLE
Missing time zone for time stamps

### ISSUE THREAD

**Issue by daniel-schel** [research-virtualfortknox/msb-client-websocket-c#2]
For timestamps the timezone is missing. This can cause errors when parsing or interpreting the data.
A Z for UTC time or +/-xx:xx depending on the time zone would be expected at the end of the timestamp.

**Comment by 408b7f8b** [comment]
#c6b449a49ec2ab517f2691166cefe429be7ebf20

**Comment by 408b7f8b** [comment]
Commit c6b449a49ec2ab517f2691166cefe429be7ebf20 should do the trick

**Comment by daniel-schel** [comment]
It works, thanks!
